plugins {
    id "com.android.application"
}

android {
    namespace "com.fengnanrui.dshandroid"
    compileSdk 35
    useLibrary "android.test.base"
    useLibrary "android.test.runner"

    defaultConfig {
        applicationId "com.fengnanrui.dshandroid"
        minSdk 28
        targetSdk 35
        versionCode 3
        versionName "1.1.0"

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.json:json:20250517"
}
